backend: 
  name: github
  repo: jessicavrooyen/netlifycms

media_folder: static/assets

collections:
  - name: project
    label: Projects
    folder: src/content/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Project, widget: markdown }